name: extraction-shooter
version: '1.0.0'
main: io.Sriptirc_wp_1441.extractionShooter.ExtractionShooter
api-version: '1.16'
authors: ['wp:1441']
description: '一个搜打撤玩法的 Forge Mod，支持背包容量限制、物品占格旋转、搜刮流程、品质系统、死亡掉落转入容器、固定/临时刷新点、撤离规则与多货币消耗等完整玩法。'
